### ISSUE TITLE
Is there some way to test/predict on new data?

### ISSUE THREAD

**Issue by wanicca** [akb89/pyfn#24]
Thanks for your hard work! 

I have a question about how to test or predict on new data. If I have some new labeled data (other than official framenet) or just want to do frame semantic parsing on unlabeled sentences using trained semafor and open-sesame, should I prepare the data in the same style as fulltext.xml and then do unmarshalling?

**Comment by akb89** [comment]
Thanks!

If you want to use multiple parsers, I think converting your original input format to `fnxml` (used in fulltext.xml) should indeed be the easiest option. Then you can use pyfn to convert from fnxml to `bios` and `semafor` and you can also convert the different output of the parsers to `semeval` format. 
I agree that this looks like a lot of extra work and entropy to convert back and from so many formats, but if sound evaluation is crucial to you this way you can really guarantee that you're comparing apples with apples and not apples with oranges...

**Comment by wanicca** [comment]
Thank you. I will have a try.
