### ISSUE TITLE
Unclear explanation on `splits` in README

### ISSUE THREAD

**Issue by akb89** [akb89/pyfn#4]
```
--splits: specify which splits should be converted. Use --splits dev to only process dev and test splits and guarantee no overlap between dev and test. Use --splits train to process train dev and test splits and guarantee no overlap across splits. Default to --splits test.
```
Is really confusing, as you say it defaults to test, which you do not explain, the example uses more than one split {test,dev} but this explanation uses just one. Is it just using part of the data or splitting all the data into 2 splits instead of three when I say {test,dev}?
The example is: 
```bash
pyfn convert \
  --from fnxml \
  --to bios \
  --source /abs/path/to/fndata-1.x \
  --target /abs/path/to/xp/data/output/dir \
  --splits train \
  --output_sentences \
  --filter overlap_fes
```

**Comment by akb89** [comment]
## Conversion HowTo
The following sections provide examples of commands to convert FN data
to and from different formats. All commands can make use of the following options:
1. `--splits`: specify which splits should be converted. `--splits train` will generate all train/dev/test splits, according to data found under the fndata-1.x/{train/dev/test} directories. `--splits dev` will generate the dev and test splits according to data found under the fndata-1.x/{dev/test} directories. This option will skip the train splits but generate the same dev/test splits that would have been generated with `--splits train`. `--splits test` will generate the test splits according to data found under the fndata-1.x/test directory, and skip the train/dev splits. The test splits generated with `--splits test` will be the same as those generated with the `--splits train` and `--splits dev`.

**Comment by jcklie** [comment]
It is much clearer now, I would just add the default case.
