### ISSUE TITLE
Document unmarshaller

### ISSUE THREAD

**Issue by jcklie** [akb89/pyfn#6]
In my application, I typically need to write parsing code to load FrameNet data. It would be nice if I just could use the data structure and code that is already in `pyfn` to load FrameNet into my application. As I assume the code for that is already there, it would just need documentation to tell users how to load FrameNet data into Python objects.

**Comment by akb89** [comment]
Good idea. The code is indeed ready (I use it for another FN-based app). We just need to document it. This should be available in v1.2.0. Release scheduled next week.

**Comment by akb89** [comment]
Documentation is now available on the README of release v1.2.0
